### ISSUE TITLE
OSError: It looks like the config file at 'J:/SD/models/stable-diffusion-v1-4.ckpt' is not a valid JSON file.

### ISSUE THREAD

**Issue by JosephBashful** [parlance-zz/g-diffuser-lib#53]
clean installation, i got this error with my model i usually use with other repo.
Here's the full output
Traceback (most recent call last):
  File "J:\MINICONDA\envs\g_diffuser\lib\site-packages\diffusers\configuration_utils.py", line 272, in get_config_dict
    config_dict = cls._dict_from_json_file(config_file)
  File "J:\MINICONDA\envs\g_diffuser\lib\site-packages\diffusers\configuration_utils.py", line 324, in _dict_from_json_file
    text = reader.read()
  File "J:\MINICONDA\envs\g_diffuser\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "J:\SD\g_diffuser_cli.py", line 206, in <module>
    main()
  File "J:\SD\g_diffuser_cli.py", line 89, in main
    gdl.load_pipelines(args)
  File "J:\SD\g_diffuser_lib.py", line 639, in load_pipelines
    pipe = pipe_map[pipe_name].from_pretrained(
  File "J:\MINICONDA\envs\g_diffuser\lib\site-packages\diffusers\pipeline_utils.py", line 290, in from_pretrained
    config_dict = cls.get_config_dict(
  File "J:\MINICONDA\envs\g_diffuser\lib\site-packages\diffusers\configuration_utils.py", line 274, in get_config_dict
    raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at 'J:/SD/models/stable-diffusion-v1-4.ckpt' is not a valid JSON file.

**Comment by olibols** [comment]
Install it like it tells you to in the README.md in the models folder. Pasting your checkpoints file is not that.

**Comment by parlance-zz** [comment]
> Install it like it tells you to in the README.md in the models folder. Pasting your checkpoints file is not that.

He speaks the truth. What you need is the _diffusers_ specific model. There are links in the models readme.
